questlog_new:
    path: /new/{public}/{deck1_id}/{deck2_id}/{deck3_id}/{deck4_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:new
        public: false
        deck1_id: null
        deck2_id: null
        deck3_id: null
        deck4_id: null
    requirements:
        public: true || false
        deck1_id: \d+
        deck2_id: \d+
        deck3_id: \d+
        deck4_id: \d+

questlog_save:
    path: /save
    methods: [POST]
    defaults:
        _controller: AppBundle:QuestLog:save

questlog_edit:
    path: /edit/{questlog_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:edit
    requirements:
        questlog_id: \d+

questlog_view:
    path: /view/{questlog_id}/{questlog_name}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:view
        questlog_name: null
    requirements:
        questlog_id: \d+

questlog_export_text:
    path: /export/text/{questlog_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:textexport
    requirements:
        questlog_id: \d+

questlog_export_octgn:
    path: /export/octgn/{questlog_id}
    methods: [GET]
    defaults:
        _controller: AppBundle:QuestLog:octgnexport
    requirements:
        questlog_id: \d+

questlog_delete:
    path: /delete
    methods: [POST]
    defaults:
        _controller: AppBundle:QuestLog:delete

questlog_delete_list:
    path: /delete_list
    methods: [POST]
    defaults:
        _controller: AppBundle:QuestLog:deleteList
        